"""A pinned C compiler for linking sysimages: zig's `zig cc`, as a repository rule.

PackageCompiler links a sysimage with a C compiler. Left to itself it takes `JULIA_CC`, or else
the first of g++, clang++, gcc and clang on PATH, which makes the host's compiler and C library
an input that no cache key covers. This repository pins both. One zig tarball, fetched by
sha256, holds the compiler, the linker and the headers and stubs of every glibc version it
supports, so `zig cc -target <arch>-linux-gnu.<glibc>` links against the same C library on
every host.

    bin/cc   the compiler to give PackageCompiler (through sysimage.sh's
             JULIA_DEPOT_SYSIMAGE_CC); a wrapper that adds the target
    :cc      bin/cc and the zig distribution it runs, for an action's inputs; also the
             default target, named after the repository

The host decides the zig build, as it does the Julia build in dist.bzl: PackageCompiler builds
a sysimage for the Julia that runs it, so the compiler targets the same architecture.

The wrapper records the zig version, its sha256 and the target, so its digest changes with
any of them. An action that declares only bin/cc is therefore still keyed on the compiler.
It also needs the rest of :cc among its inputs, or a sandboxed action cannot find zig.

`glibc` is the oldest glibc a sysimage built with it loads on. The default, 2.17, is what the
official Julia builds target. A sysimage needs only the symbols libjulia already needs, so a
lower target costs nothing.
"""

load(":dist.bzl", "host_platform")

DEFAULT_CC_VERSION = "0.16.0"
DEFAULT_CC_GLIBC = "2.17"
DEFAULT_CC_URL = "https://ziglang.org/download/{version}/zig-{arch}-linux-{version}.tar.xz"
DEFAULT_CC_STRIP_PREFIX = "zig-{arch}-linux-{version}"

# Official tarballs, by version and platform, from https://ziglang.org/download/index.json. Add
# a version here, or pass `sha256 = {"<platform>": ...}` on the tag for any version or mirror.
_KNOWN_SHA256 = {
    "0.16.0": {
        "linux-aarch64": "ea4b09bfb22ec6f6c6ceac57ab63efb6b46e17ab08d21f69f3a48b38e1534f17",
        "linux-x86_64": "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00",
    },
}

_WRAPPER = """#!/usr/bin/env bash
# Generated by julia_depot's julia.cc: a C compiler for linking sysimages.
#   zig {version} ({platform}, sha256 {sha256}), targeting {triple}
set -euo pipefail

zig="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)/zig/zig"

# A private cache per run: zig's default is under $HOME, state shared across builds.
cache="$(mktemp -d)"
trap 'rm -rf "$cache"' EXIT

args=()
for a in "$@"; do
    case "$a" in
        # GCC's spellings (x86-64, armv8-a+crypto+simd), which zig reads as CPU names. A link
        # compiles nothing, so dropping the flag changes nothing.
        -march=*) ;;
        *) args+=("$a") ;;
    esac
done

ZIG_GLOBAL_CACHE_DIR="$cache" ZIG_LOCAL_CACHE_DIR="$cache" \\
    "$zig" cc -target {triple} "${{args[@]}}"
"""

_BUILD = """
filegroup(
    name = "cc",
    srcs = ["bin/cc"] + glob(["zig/**"]),
    visibility = ["//visibility:public"],
)

exports_files(["bin/cc"])
"""

# The default target, so `@<name>` alone means the compiler and everything it runs.
_ALIAS = """
alias(
    name = "{name}",
    actual = ":cc",
    visibility = ["//visibility:public"],
)
"""

def _expand(template, subs):
    out = template
    for k, v in subs.items():
        out = out.replace(k, v)
    return out

def check_glibc(what, glibc):
    """Fails unless `glibc` is a version such as 2.17.

    Args:
      what: the rule or tag to name in the error.
      glibc: the version string.
    """
    parts = glibc.split(".")
    if len(parts) != 2 or not parts[0].isdigit() or not parts[1].isdigit():
        fail("{}: glibc = \"{}\" is not a version such as \"2.17\"".format(what, glibc))

def _julia_cc_impl(rctx):
    platform, _ = host_platform(rctx.os.name, rctx.os.arch, "julia.cc")
    arch = platform[len("linux-"):]
    version = rctx.attr.version
    check_glibc("julia.cc", rctx.attr.glibc)
    subs = {"{arch}": arch, "{version}": version}

    sha256 = rctx.attr.sha256.get(platform) or _KNOWN_SHA256.get(version, {}).get(platform)
    if not sha256:
        fail(("julia.cc: no known sha256 for zig {} on {}; pass sha256 = {{\"{}\": ...}} from " +
              "https://ziglang.org/download/index.json").format(version, platform, platform))

    rctx.download_and_extract(
        url = _expand(rctx.attr.url, subs),
        sha256 = sha256,
        strip_prefix = _expand(rctx.attr.strip_prefix, subs),
        output = "zig",
    )
    rctx.file("bin/cc", _WRAPPER.format(
        version = version,
        platform = platform,
        sha256 = sha256,
        triple = "{}-linux-gnu.{}".format(arch, rctx.attr.glibc),
    ), executable = True)
    name = rctx.original_name
    rctx.file("BUILD.bazel", _BUILD + ("" if name == "cc" else _ALIAS.format(name = name)))

julia_cc = repository_rule(
    implementation = _julia_cc_impl,
    attrs = {
        "version": attr.string(default = DEFAULT_CC_VERSION, doc = "zig version."),
        "glibc": attr.string(default = DEFAULT_CC_GLIBC, doc = "The glibc version to link against: the oldest a sysimage loads on."),
        "sha256": attr.string_dict(doc = "Tarball sha256 by platform (linux-x86_64, linux-aarch64). Optional for versions this module knows."),
        "url": attr.string(default = DEFAULT_CC_URL, doc = "Tarball URL template; {version} and {arch} expand."),
        "strip_prefix": attr.string(default = DEFAULT_CC_STRIP_PREFIX, doc = "Archive prefix template, expanded like `url`."),
    },
    doc = "Downloads zig for the host, pinned by sha256, and wraps `zig cc` to link sysimages against a fixed glibc.",
)
